### ISSUE TITLE
Use the PERMISSION in settings.py of groups_manager to standard

### ISSUE THREAD

**Issue by Allan-Nava** [vittoriozamboni/django-groups-manager#24]
Hi @OskarPersson ,

I would need that when a user is associated with the staff or referent role can have the privileges of being able to modify the group, add users or remove them both for the belonging group and the children of the group.

It's possible?

```
from django.conf import settings

GROUPS_MANAGER_SETTINGS = getattr(settings, 'GROUPS_MANAGER', {})

SETTINGS_PERMISSIONS = GROUPS_MANAGER_SETTINGS.get('PERMISSIONS', {})

PERMISSIONS = {
    #'owner': ['view', 'change', 'delete',],
    'owner': {
        'leader': ['change', 'delete'], 
        'referent': ['change', 'delete'],
        'default': ['view', 'change', 'delete',],
    },
    'group': ['view', 'change',],
    #'groups_upstream': ['view'],
    #'groups_downstream': ,
    'groups_upstream': {
        'leader': ['change', 'delete'], 
        'referent': ['change', 'delete'], 
        'default': ['view']
    },
    'groups_downstream': {
        'leader': ['change', 'delete'], 
        'referent': ['change', 'delete'], 
        'default': ['view']
    },
    'groups_siblings': ['view'],
}
PERMISSIONS.update(SETTINGS_PERMISSIONS)

GROUPS_MANAGER = {
    # User and Groups sync settings
    'AUTH_MODELS_SYNC': GROUPS_MANAGER_SETTINGS.get('AUTH_MODELS_SYNC', False),
    'AUTH_MODELS_GET_OR_CREATE': GROUPS_MANAGER_SETTINGS.get('AUTH_MODELS_GET_OR_CREATE', True),
    'GROUP_NAME_PREFIX': GROUPS_MANAGER_SETTINGS.get('GROUP_NAME_PREFIX', 'DGM_'),
    'GROUP_NAME_SUFFIX': GROUPS_MANAGER_SETTINGS.get('GROUP_NAME_SUFFIX', '_$$random'),
    'USER_USERNAME_PREFIX': GROUPS_MANAGER_SETTINGS.get('USER_USERNAME_PREFIX', 'DGM_'),
    'USER_USERNAME_SUFFIX': GROUPS_MANAGER_SETTINGS.get('USER_USERNAME_SUFFIX', '_$$random'),
    # Permissions
    'PERMISSIONS': PERMISSIONS,
    # Templates
    'TEMPLATE_STYLE': GROUPS_MANAGER_SETTINGS.get('TEMPLATE_STYLE', 'bootstrap3')
}

```

My problem is how does the GROUPS_MANAGER ['PERMISSIONS'] work?

**Comment by aaarghhh** [comment]
I think you have to use:  'AUTH_MODELS_SYNC': True, in order to make PERMISSION work. 
This is a condition to make the guardian app working.

**Comment by Allan-Nava** [comment]
@aaarghhh  but default is not True?

**Comment by Allan-Nava** [comment]
@aaarghhh ok, now i swap this:
`'AUTH_MODELS_SYNC': GROUPS_MANAGER_SETTINGS.get('AUTH_MODELS_SYNC', False),`
to `True`

**Comment by aaarghhh** [comment]
> `AUTH_MODELS_SYNC': GROUPS_MANAGER_SETTINGS.get('AUTH_MODELS_SYNC', False`)

 , seems it's take False at default.

**Comment by Allan-Nava** [comment]
Ok @aaarghhh , I update my settings.py:
```
from django.conf import settings

GROUPS_MANAGER_SETTINGS = getattr(settings, 'GROUPS_MANAGER', {})

SETTINGS_PERMISSIONS = GROUPS_MANAGER_SETTINGS.get('PERMISSIONS', {})
PERMISSIONS = {
    #'owner': ['view', 'change', 'delete',],
    'owner': {
        'leader': ['change', 'delete'], 
        'referent': ['change', 'delete'],
        'default': ['view', 'change', 'delete',],
    },
    'group': ['view', 'change',],
    #'groups_upstream': ['view'],
    #'groups_downstream': ,
    'groups_upstream': {
        'leader': ['change', 'delete'], 
        'referent': ['change', 'delete'], 
        'default': ['view']
    },
    'groups_downstream': {
        'leader': ['change', 'delete'], 
        'referent': ['change', 'delete'], 
        'default': ['view']
    },
    'groups_siblings': ['view'],
}
PERMISSIONS.update(SETTINGS_PERMISSIONS)
GROUPS_MANAGER = {
    # User and Groups sync settings
    'AUTH_MODELS_SYNC': GROUPS_MANAGER_SETTINGS.get('AUTH_MODELS_SYNC', True),
    'AUTH_MODELS_GET_OR_CREATE': GROUPS_MANAGER_SETTINGS.get('AUTH_MODELS_GET_OR_CREATE', True),
    'GROUP_NAME_PREFIX': GROUPS_MANAGER_SETTINGS.get('GROUP_NAME_PREFIX', 'DGM_'),
    'GROUP_NAME_SUFFIX': GROUPS_MANAGER_SETTINGS.get('GROUP_NAME_SUFFIX', '_$$random'),
    'USER_USERNAME_PREFIX': GROUPS_MANAGER_SETTINGS.get('USER_USERNAME_PREFIX', 'DGM_'),
    'USER_USERNAME_SUFFIX': GROUPS_MANAGER_SETTINGS.get('USER_USERNAME_SUFFIX', '_$$random'),
    # Permissions
    'PERMISSIONS': PERMISSIONS,
    # Templates
    'TEMPLATE_STYLE': GROUPS_MANAGER_SETTINGS.get('TEMPLATE_STYLE', 'bootstrap3')
}
```

But when i try to use **assign_object** programmatically doesn't work and I got this erorr:
![screen shot 2017-12-15 at 14 30 17](https://user-images.githubusercontent.com/22498435/34044265-8e7704a4-e1a4-11e7-8d32-e74b3eb439b5.png)

**Comment by aaarghhh** [comment]
`juve.add_member(mem) `

**Comment by Allan-Nava** [comment]
Yeah, I forgot and I thought he was already a member.

But is possible associate the permission for member role, so if I have the role referent the member (mem) has automatically the permission of referent?

![screen shot 2017-12-15 at 14 46 18](https://user-images.githubusercontent.com/22498435/34044805-ca99f980-e1a6-11e7-90fa-4dc5a942489d.png)
I have got the error 

Thanks for support @aaarghhh

**Comment by Allan-Nava** [comment]
The problem is method: **assign_perm** of django guardian

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/home/ies/bootcamp/bootcamp/groups_manager/models.py", line 145, in assign_object
    return assign_object_to_member(group_member, obj, **kwargs)
  File "/home/ies/bootcamp/bootcamp/groups_manager/perms.py", line 49, in assign_object_to_member
    assign_perm(perm_name, group_member.member.django_user, obj)
  File "/usr/local/lib/python3.5/dist-packages/guardian/shortcuts.py", line 105, in assign_perm
    return model.objects.assign_perm(perm, user, obj)
  File "/usr/local/lib/python3.5/dist-packages/guardian/managers.py", line 39, in assign_perm
    permission = Permission.objects.get(content_type=ctype, codename=perm)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: Permission matching query does not exist.
```

https://github.com/django-guardian/django-guardian/issues/540

**Comment by ad-m** [comment]
@Allan-Nava , do you can extract test case, provide expected input & output of ```assign_perm```?

**Comment by Allan-Nava** [comment]
@ad-m , Of course!

Wait you need the [django-groups-manager](https://github.com/vittoriozamboni/django-groups-manager/) and setup the **settings.py** with:
```
from django.conf import settings

GROUPS_MANAGER_SETTINGS = getattr(settings, 'GROUPS_MANAGER', {})

SETTINGS_PERMISSIONS = GROUPS_MANAGER_SETTINGS.get('PERMISSIONS', {})
PERMISSIONS = {
    #'owner': ['view', 'change', 'delete',],
    'owner': {
        'leader': ['change', 'delete'], 
        'referent': ['change', 'delete'],
        'default': ['view', 'change', 'delete',],
    },
    'group': ['view', 'change',],
    #'groups_upstream': ['view'],
    #'groups_downstream': ,
    'groups_upstream': {
        'leader': ['change', 'delete'], 
        'referent': ['change', 'delete'], 
        'default': ['view']
    },
    'groups_downstream': {
        'leader': ['change', 'delete'], 
        'referent': ['change', 'delete'], 
        'default': ['view']
    },
    'groups_siblings': ['view'],
}
PERMISSIONS.update(SETTINGS_PERMISSIONS)
GROUPS_MANAGER = {
    # User and Groups sync settings
    'AUTH_MODELS_SYNC': GROUPS_MANAGER_SETTINGS.get('AUTH_MODELS_SYNC', True),
    'AUTH_MODELS_GET_OR_CREATE': GROUPS_MANAGER_SETTINGS.get('AUTH_MODELS_GET_OR_CREATE', True),
    'GROUP_NAME_PREFIX': GROUPS_MANAGER_SETTINGS.get('GROUP_NAME_PREFIX', 'DGM_'),
    'GROUP_NAME_SUFFIX': GROUPS_MANAGER_SETTINGS.get('GROUP_NAME_SUFFIX', '_$$random'),
    'USER_USERNAME_PREFIX': GROUPS_MANAGER_SETTINGS.get('USER_USERNAME_PREFIX', 'DGM_'),
    'USER_USERNAME_SUFFIX': GROUPS_MANAGER_SETTINGS.get('USER_USERNAME_SUFFIX', '_$$random'),
    # Permissions
    'PERMISSIONS': PERMISSIONS,
    # Templates
    'TEMPLATE_STYLE': GROUPS_MANAGER_SETTINGS.get('TEMPLATE_STYLE', 'bootstrap3')
}
```

You can create with:
```
from django.contrib.auth.models import User
from groups_manager.models import Member, Member, Group

a = User.objects.create(username="allan")
m = Member.objects.create(django_user=a)
inter = Group.objects.create(name="inter")

inter.add_member(m)
m.assign_object(inter, inter, custom_permission={'group': ['play']})
```

**Comment by Giovanni-94** [comment]
Hi @ad-m @Allan-Nava more and less I have the same problem

**Comment by vittoriozamboni** [comment]
Hi guys, sorry for the late answer. I am don't really understand which is the problem.
It seems that the permission has not been created: 
```python
class MyGroup(Group):
    name = models.CharField(max_length=100)

    class Meta:
        permissions = (
                       ('play_mygroup', 'Play MyGroup'),
                       ('other_mygroup', 'Other MyGroup'),
        )
```
After this, you need to do a migration of your app (if I remember well). 

@Allan-Nava , it seems you are editing directly the settings.py of the application - you should configure them through the settings instead: http://django-groups-manager.readthedocs.io/en/latest/settings.html

**Comment by vittoriozamboni** [comment]
In addition, if you switch the sync from False to True you need to trigger the creation of the previous entries (they will not be automatically created). To do so, save all your previously created groups and members (you can do that in the shell).

```python
for m in Member.objects.all():
    m.save()

for g in Group.objects.all():
    g.save()

for gm in GroupMember.objects.all():
    gm.save()
```
