### ISSUE TITLE
Issue "on delete" - first installation

### ISSUE THREAD

**Issue by Emanuele94** [vittoriozamboni/django-groups-manager#25]
:\Users\Emauele Di Molfetta\Desktop\ALLAN\django>python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\Emauele Di Molfetta\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\core\management\__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "C:\Users\Emauele Di Molfetta\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\core\management\__init__.py", line 347, in execute
    django.setup()
  File "C:\Users\Emauele Di Molfetta\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\Emauele Di Molfetta\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\apps\registry.py", line 112, in populate
    app_config.import_models()
  File "C:\Users\Emauele Di Molfetta\AppData\Local\Programs\Python\Python36-32\lib\site-packages\django\apps\config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Users\Emauele Di Molfetta\AppData\Local\Programs\Python\Python36-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Emauele Di Molfetta\AppData\Local\Programs\Python\Python36-32\lib\site-packages\groups_manager\models.py", line 295, in <module>
    class GroupMixin(GroupRelationsMixin, MPTTModel):
  File "C:\Users\Emauele Di Molfetta\AppData\Local\Programs\Python\Python36-32\lib\site-packages\groups_manager\models.py", line 326, in GroupMixin
    related_name='sub_%(app_label)s_%(class)s_set')
TypeError: __init__() missing 1 required positional argument: 'on_delete'

**Comment by Allan-Nava** [comment]
Any news?

**Comment by srtonz** [comment]
Since v2.0 Django requires the `on_delete` parameter on all many-to-one relations. You can either downgrade to Django<2.0 or manually patch this module by first adding the old default `on_delete=models.CASCADE` to all failing lines and then re-creating the migrations.

@vittoriozamboni are you planning to release a Django 2.0+ compatible version?

**Comment by Allan-Nava** [comment]
@GeoTob Thanks for support! It needs bugfix ???

**Comment by vittoriozamboni** [comment]
@GeoTob sure! 
For some reason I didn't notice these issues opened after mid December. I am working on a fix for this.
@Allan-Nava will try to fix it this week, otherwise for mid of the next one.

**Comment by Allan-Nava** [comment]
@vittoriozamboni Thank's let me know when you bugfixed this error!

**Comment by vittoriozamboni** [comment]
@Allan-Nava version 0.6.1 has been uploaded and should contains the necessary fixes for Django 2.

**Comment by Allan-Nava** [comment]
Thanks, how can I update the library?

Inviato da iPhone

**Comment by vittoriozamboni** [comment]
You can use pip: `pip install django-groups-manager --upgrade`. Don't forget to run migrations after.
