### ISSUE TITLE
ValueError: "<Group: Compravo>" needs to have a value for field "id" before this many-to-many relationship can be used.

### ISSUE THREAD

**Issue by Allan-Nava** [vittoriozamboni/django-groups-manager#26]
How can I fix?

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ies/bootcamp/bootcamp/authentication/views.py", line 422, in create_society
    fsociety = Group(**form.cleaned_data)
  File "/usr/local/lib/python3.5/dist-packages/mptt/models.py", line 388, in __init__
    super(MPTTModel, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/base.py", line 567, in __init__
    _setattr(self, prop, kwargs[prop])
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/fields/related_descriptors.py", line 536, in __set__
    manager = self.__get__(instance)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/fields/related_descriptors.py", line 513, in __get__
    return self.related_manager_cls(instance)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/fields/related_descriptors.py", line 830, in __init__
    (instance, self.pk_field_names[self.source_field_name]))
ValueError: "<Group: Compravo>" needs to have a value for field "id" before this many-to-many relationship can be used.
```

**Comment by vittoriozamboni** [comment]
Hi @Allan-Nava , how did you produced this error? Is still an issue?
Really sorry for the late reply.

**Comment by vittoriozamboni** [comment]
Closing the issue.
